---
- hosts: beppe
  sudo: no
  user: root
  vars:
    beppehome: /var/beppe
  tasks:
    - name: enable multiverse repository
      apt_repository: repo='deb http://nova.clouds.archive.ubuntu.com/ubuntu/ ${ansible_lsb.codename} multiverse' state=present

    - name: update cache of the APT repository
      apt: update_cache=yes

    - name: Install required DEB packages
      apt: pkg=$item state=installed 
      with_items: 
        - python-dev
        - build-essential
        - libxslt1-dev
        - libxml2-dev
        - git
        - python-virtualenv
        - apache2
        - libapache2-mod-fastcgi

    - name: Ensure that $beppehome directory exists
      file: path=$beppehome state=directory

    - name: download software from GIT repository
      git: repo=git://github.com/arcimboldo/beppecrawler.git dest=$beppehome

    - name: Create Virtual Environment
      pip: name=$item virtualenv=$beppehome/venv
      with_items:
        - scrapy
        - pytz
        - django
        - flup
        - sqlalchemy

    - name: configure beppegrillo package
      lineinline: dest=$beppehome/crawler/settings.py regexp=SQLDB_OFFLINE_URI.* line='SQLDB_OFFLINE_URI="sqlite:///$beppehome/beppegrillo.offline.db"'

    - name: Install beppegrillo package
      shell: "bash -c '. $beppehome/venv/bin/activate; cd $beppehome; python setup.py install'"

    - name: Setup cron job to crawl beppegrillo site
      cron: name="run beppe crawler" minute="*/10" job="bash -c '. $beppehome/venv/bin/activate; rm beppegrillo.log; cd $beppehome/; scrapy crawl beppegrillo --logfile=beppegrillo.log; cp beppegrillo.db beppegrillo.offline.db; chmod a+r beppegrillo.offline.db'"

    - name: Install initscript for django application
      template: src=initscript.j2 dest=$beppehome/webgui/restartcgi mode=0755
      
    - name: Install settings script for django application
      lineinfile: dest=$beppehome/webgui/settings.py regexp='^VIRTUALENV=.*' line='VIRTUALENV="$beppehome/venv"'
      tags: now

    - name: Ensure that the django application is running
      shell: $beppehome/webgui/restartcgi

    - name: ensure rewrite module is installed
      shell: a2enmod rewrite
      notify: restart apache

    - name: Setup apache (1/3)
      lineinfile: dest=/etc/apache2/httpd.conf regexp="^FastCGIExternalServer.*beppe.fcgi.*" line="FastCGIExternalServer /var/www/beppe.fcgi -host 127.0.0.1:1234"
      notify: restart apache

    - name: Setup apache (2/3)
      lineinfile: dest=/etc/apache2/httpd.conf regexp="^RewriteEngine on" line="RewriteEngine on"
      notify: restart apache

    - name: Setup apache (3/3)
      lineinfile: dest=/etc/apache2/httpd.conf regexp="^RewriteRule .*beppe.*" line="RewriteRule ^(.*)$ /beppe.fcgi/$1 [QSA,L]"
      notify: restart apache

  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
      

